### ISSUE TITLE
Expose algorithm parameters

### ISSUE THREAD

**Issue by FreakTheMighty** [Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction#2]
I think it would be helpful to expose the parameters [here](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/eca167ac1c51b21e01af5a15f1c2e979b334fffe/src.cmd/Simplify.h#L378). Specifically the `0.000000001` scale parameter would help tune quality.

I also think it'd be cool to expose the update rate of the mesh [here](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/blob/eca167ac1c51b21e01af5a15f1c2e979b334fffe/src.cmd/Simplify.h#L364). I believe the frequency of update has an impact on the quality vs. performance trade of.

Thoughts?

**Comment by Kramer84** [comment]
I agree, the more control we have over the algorithm, the better. 

Exposing most of them through new keyword arguments in the simplify_mesh function is the easiest way to go I think. At the same time I'll expose the simplify_mesh_lossless method.

As soon as I have some time I get to it.

**Comment by FreakTheMighty** [comment]
I saw that `simplify_mesh_lossless` method, but couldn't quite make out what makes it loseless. Any chance you can explain that to me?

**Comment by FreakTheMighty** [comment]
BTW, the biggest  quality issue I've had so far seems to be around boundary preservation.  On the mesh sample I shared previously I get holes. I'm hoping that playing with these parameters I can improve the quality, but it may require some other adjustments. I know that other implementations weight vertices on boundaries so that they are removed last.

**Comment by Kramer84** [comment]
I have not yet tried out the `simplify_mesh_lossless` method, but from as far that I see, the biggest difference between the two is that the threshold does not change at every iteration and that the mesh is updated at every loop. 
This updating behaviour by the way would just be the case where we had the update_rate of the `simplify_mesh` method set to 1. 
An other big difference is that we have no target count. The mesh will be reduced until nothing more can be simplified without exceeding the threshold error. 
So it's not entirely lossless, but the loss will never be above the threshold specified. 

It may be more convenient to set this behaviour through other keywords in the `simplify_mesh` method,  rather than adding a completely new function... 
But the two possibilities are viable.

For other options as weighing the vertices on the boundaries, I don't know to what extent we would have to modify the C++ script, as I am no expert in mesh decimation nor C++. But I believe that we could force the code to never delete vertices having certain coordinates.

**Comment by FreakTheMighty** [comment]
I think vertex.border may indicate whether it belongs to a boundary. [This issue](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/issues/14) seems to capture one portion of improving boundary preservation. I think I prefer the idea again of having a mechanism to weight "borders", rather than fully "lock" them.

To your other point, if the "lossless" function is essentially copying the `simplify_mesh` function but with other parameters, then I don't think its worth exposing. It seems cleaner to simply expose those params.

**Comment by Kramer84** [comment]
In the new `simplify_mesh` method, I exposed most of the parameters that were in the C++ method. The new constructor is: 
`
simplify_mesh(int target_count, int update_rate, double aggressiveness, int  max_iterations, bool verbose, bool lossless, double threshold_lossless, double alpha, int K, bool preserve_border)
`
When lossless is set to true it forces to update the mesh at each iteration, and fixes the threshold, but doing so completely destroys the bunny sample. I don't know where this error comes from. 

When preserve_bool is set to true, it uses the border check function mentioned in [the issue](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification/issues/14). 

The parameters alpha, K and aggressiveness control the threshold growth rate, when not in lossless mode: 
`
threshold = alpha*pow( iteration + K, agressiveness)
`

I have not played a lot around with the parameters but it seems that some configurations produce broken meshes.

If you can think of other parameters to expose I can add them as well.

Also, on the side note, I had used the [meshFix](https://github.com/pyvista/pymeshfix) algorithm, which manages to repair closed meshes and gets them watertight (if the holes are not to big). I don't know if trimesh implements already something like that but it could be a neat addition.
